{{- if .Values.api.dynamicCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-dynamic-credentials
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
type: Opaque
data:
  public-key.pem: {{ .Values.api.dynamicCredentials.publicKey | b64enc }}
  private-key.pem: {{ .Values.api.dynamicCredentials.privateKey | b64enc }}
{{- end }}