{{- if and .Values.ingress.executor.enabled (eq .Values.ingress.controller "gatewayapi") }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name }}-executor
  labels:
    app: {{ .Values.name }}-executor
{{- with .Values.ingress.executor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
{{- with .Values.ingress.executor.domain }}
  hostnames:
    - {{ . | quote }}
{{- end }}
{{- with .Values.ingress.gatewayapi.gateways}}
  parentRefs: {{- . | toYaml | nindent 4 }}
{{- end }}
  rules:
  - backendRefs:
    - kind: Service
      name: {{ .Values.name }}-executor-service
      port: 8090
    matches:
    - path:
      type: pathPrefix
      values: {{ .Values.ingress.executor.path  }}
{{- end }}
