{{- if and .Values.api.enabled (not .Values.api.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-api-secrets
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
type: Opaque
stringData:
  PatSecret: '{{ .Values.security.patSecret | b64enc }}'
  InternalSecret: '{{ .Values.security.internalSecret | b64enc }}'
  DexClientId: '{{ .Values.security.dexClientId }}'
  {{- if .Values.api.defaultRedis }}
  #Default Redis
  TerrakubeRedisPassword: {{ .Values.redis.auth.password }}
  {{- else }}
  #Custom Redis
  TerrakubeRedisPassword: '{{ .Values.api.properties.redisPassword }}'
  {{- end }}

  {{- if .Values.storage.defaultStorage }}

  #AWS S3 Storage (default minio)
  AwsStorageAccessKey: '{{ .Values.minio.auth.rootUser }}'
  AwsStorageSecretKey: '{{ .Values.minio.auth.rootPassword }}'

  {{- else }}

  {{- if and (.Values.storage.azure).storageAccountName (.Values.storage.azure).storageAccountAccessKey }}
  #Azure Storage
  AzureAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}

  {{- if and (.Values.storage.aws).bucketName (.Values.storage.aws).region }}
  #AWS S3 Storage
  {{- if and (.Values.storage.aws).accessKey (.Values.storage.aws).secretKey }}
  AwsStorageAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsStorageSecretKey: '{{ .Values.storage.aws.secretKey }}'
  {{- end }}
  {{- end }}

  {{- if and (.Values.storage.minio).bucketName (.Values.storage.minio).accessKey (.Values.storage.minio).secretKey (.Values.storage.minio).endpoint }}
  #MINIO S3 Storage
  AwsStorageAccessKey: '{{ .Values.storage.minio.accessKey }}'
  AwsStorageSecretKey: '{{ .Values.storage.minio.secretKey }}'
  {{- end }}

  {{- if and (.Values.storage.gcp).projectId (.Values.storage.gcp).bucketName (.Values.storage.gcp).credentials }}
  #GCP Storage Bucket
  GcpStorageCredentialsBase64: {{ .Values.storage.gcp.credentials | b64enc }}
  {{- end }}

  {{- end }}

  {{- if .Values.api.defaultDatabase }}
  #Checking default database options
  DatasourcePassword: '{{ .Values.postgresql.auth.password }}'
  {{- else }}
  DatasourcePassword: '{{ .Values.api.properties.databasePassword }}'
  {{- end }}

{{ end }}
