{{- if and .Values.executor.enabled (not .Values.executor.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-executor-secrets
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
type: Opaque
stringData:
  InternalSecret: '{{ .Values.security.internalSecret | b64enc }}'
  {{- if .Values.api.defaultRedis }}
  #Default Redis
  TerrakubeRedisPassword: '{{ .Values.redis.auth.password }}'
  {{- else }}
  #Custom Redis
  TerrakubeRedisPassword: '{{ .Values.api.properties.redisPassword }}'
  {{- end }}

  {{- if .Values.storage.defaultStorage }}

  #AWS S3 Storage using MINIO
  AwsTerraformStateAccessKey: '{{ .Values.minio.auth.rootUser }}'
  AwsTerraformStateSecretKey: '{{ .Values.minio.auth.rootPassword }}'
  AwsTerraformOutputAccessKey: '{{ .Values.minio.auth.rootUser }}'
  AwsTerraformOutputSecretKey: '{{ .Values.minio.auth.rootPassword }}'

  {{- else }}

  {{- if and (.Values.storage.azure).storageAccountName (.Values.storage.azure).storageAccountAccessKey }}
  #Azure Storage
  AzureTerraformStateStorageAccessKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  AzureTerraformOutputAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}

  {{- if and (.Values.storage.aws).bucketName (.Values.storage.aws).region }}
  #AWS S3 Storage
  {{- if and (.Values.storage.aws).accessKey (.Values.storage.aws).secretKey }}
  AwsTerraformStateAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsTerraformStateSecretKey: '{{ .Values.storage.aws.secretKey }}'
  AwsTerraformOutputAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsTerraformOutputSecretKey: '{{ .Values.storage.aws.secretKey }}'
  {{- end }}
  {{- end }}

  {{- if and (.Values.storage.minio).bucketName (.Values.storage.minio).accessKey (.Values.storage.minio).secretKey (.Values.storage.minio).endpoint }}
  #MINIO S3 Storage
  AwsTerraformStateAccessKey: '{{ .Values.storage.minio.accessKey }}'
  AwsTerraformStateSecretKey: '{{ .Values.storage.minio.secretKey }}'
  AwsTerraformOutputAccessKey: '{{ .Values.storage.minio.accessKey }}'
  AwsTerraformOutputSecretKey: '{{ .Values.storage.minio.secretKey }}'
  {{- end }}

  {{- if and (.Values.storage.gcp).projectId (.Values.storage.gcp).bucketName (.Values.storage.gcp).credentials }}
  #GCP Storage Bucket
  GcpTerraformStateCredentials: '{{ .Values.storage.gcp.credentials | b64enc }}'
  GcpTerraformOutputCredentials: '{{ .Values.storage.gcp.credentials | b64enc }}'
  {{- end }}

  {{- end }}

{{ end }}
