{{- if and .Values.registry.enabled (not .Values.registry.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: terrakube-registry-secrets
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
type: Opaque
stringData:
  PatSecret: '{{ .Values.security.patSecret | b64enc}}'
  InternalSecret: '{{ .Values.security.internalSecret | b64enc }}'
  AppClientId: '{{ .Values.security.dexClientId }}'

  {{- if .Values.storage.defaultStorage }}

  #AWS S3 Storage using MINIO
  AwsStorageAccessKey: '{{ .Values.minio.auth.rootUser }}'
  AwsStorageSecretKey: '{{ .Values.minio.auth.rootPassword }}'

  {{- else }}

  {{- if and (.Values.storage.azure).storageAccountName (.Values.storage.azure).storageAccountAccessKey }}
  #Azure Storage
  AzureAccountKey: '{{ .Values.storage.azure.storageAccountAccessKey }}'
  {{- end }}

  {{- if and (.Values.storage.aws).bucketName (.Values.storage.aws).region }}
  #Aws Storage
  {{- if and (.Values.storage.aws).accessKey (.Values.storage.aws).secretKey }}
  AwsStorageAccessKey: '{{ .Values.storage.aws.accessKey }}'
  AwsStorageSecretKey: '{{ .Values.storage.aws.secretKey }}'
  {{- end }}
  {{- end }}

  {{- if and (.Values.storage.minio).bucketName (.Values.storage.minio).accessKey (.Values.storage.minio).secretKey (.Values.storage.minio).endpoint }}
  #MINIO Storage
  AwsStorageAccessKey: '{{ .Values.storage.minio.accessKey }}'
  AwsStorageSecretKey: '{{ .Values.storage.minio.secretKey }}'
  {{- end }}

  {{- if and (.Values.storage.gcp).projectId (.Values.storage.gcp).bucketName (.Values.storage.gcp).credentials }}
  #Gcp Storage
  GcpStorageCredentialsBase64: '{{ .Values.storage.gcp.credentials | b64enc }}'
  {{- end }}

  {{- end }}

{{ end }}
